# Generated by Django 3.0.1 on 2020-01-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nationalCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=10)),
                ('cityName', models.CharField(max_length=10)),
                ('countyName', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('center', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('probe', models.CharField(max_length=3)),
                ('silhouetteScore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='traceRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceIP', models.CharField(max_length=16)),
                ('targetIP', models.CharField(max_length=16)),
                ('TTL', models.IntegerField()),
                ('time', models.FloatField()),
                ('routers', models.CharField(max_length=1024)),
                ('stability', models.CharField(max_length=50)),
                ('sourceCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.nationalCity')),
            ],
        ),
    ]
