# Generated by Django 3.0.1 on 2020-01-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_usermodel_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='update_time',
            new_name='updateTime',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_name',
            new_name='userName',
        ),
    ]
